### ISSUE TITLE
Remove `node_modules` directory

### ISSUE THREAD

**Issue by sugyan** [Kiryuanzu/cli-slot#1]
`.gitignore` に指定されているにもかかわらず `node_modules` ディレクトリがcommitされています (`.gitignore` が後から追加されたから？)。
GitHubからリポジトリ作成すると最初に選べますが 言語ごとの `.gitignore` は https://github.com/github/gitignore/blob/master/Node.gitignore を使ったりすると良いと思います

**Comment by Kiryuanzu** [comment]
ありがとうございます！
`.gitignore`の中身を教えていただいたリンクを元に修正してみました。

`node_modules`ディレクトリもcommitされているままだと不自然だったので、`git rm --cached node_modules`で削除しておきました〜。
